create table if not exists category_forge_bundles (
  bundle_id uuid primary key,
  customer_id text not null,
  bundle_version integer not null,
  created_at timestamptz not null,
  created_by text not null,
  taxonomy jsonb not null,
  policy jsonb not null,
  model_compatibility jsonb not null,
  metadata jsonb not null,
  content_sha256 text not null,
  hmac_sha256 text,
  unique(customer_id, bundle_version)
);

create table if not exists category_forge_readiness (
  id bigint generated by default as identity primary key,
  customer_id text not null,
  ready boolean not null,
  score double precision not null,
  taxonomy_coverage double precision not null,
  auto_map_precision double precision,
  review_rate double precision not null,
  unmapped_rate double precision not null,
  historical_route_agreement double precision,
  projected_manual_review_rate double precision,
  blockers jsonb not null,
  recommendations jsonb not null,
  created_at timestamptz default now()
);

create table if not exists category_forge_deployments (
  deployment_id uuid primary key,
  customer_id text not null,
  site_id text not null,
  bundle_version integer not null,
  bundle_sha256 text not null,
  state text not null,
  canary_percent integer not null,
  previous_bundle_version integer,
  updated_at timestamptz not null
);
